[package]
name = "sunstede"
version = "0.1.0"
authors = ["Jack Byrne <jack.byrne@durham.ac.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jacl = { git = "https://github.com/jgbyrne/jacl-rs" }
